// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makedatetimepropertiesnullable20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makedatetimepropertiesnullable20));
        
        string IMigrationMetadata.Id
        {
            get { return "201711172322350_make datetime properties nullable 2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
